<a href="https://colab.research.google.com/github/henrykibithia8-dev/DS-projests/blob/main/scaling_data_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/henrykibithia8-dev/raw-files/main/Multiple%20linear%20regression.csv")
data

     SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [4]:
X = data.drop(["GPA"], axis = 1)
y = data["GPA"]

In [5]:
X

     SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [6]:
#import standard scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [7]:
#fit scaler in our x data
scaler.fit(X)

StandardScaler()

In [8]:
#transform our data
x_scaled = scaler.transform(X)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984, -1.24637147],
       [-0.4934606 , -0.07002087],
       [-0.73406132, -1.24637147],
       [ 0.85390339, -1.24637147],
       [-0.67631715, -1.24637147],
       [ 0.09360513,  1.10632974],
       [ 0.33420585, -0.07002087],
       [ 0.03586096, -0.07002087],
       [-0.35872421,  1.10632974],
       [ 1.04638396,  1.10632974],
       [-0.65706909,  1.10632974],
       [-0.13737155, -0.07002087],
       [ 0.18984542,  1.10632974],
       [ 0.04548499, -1.24637147],
       [ 1.1618723 ,  1.10632974],
       [-1.37887123, -1.24637147],
       [ 1.39284898, -1.24637147],
       [ 0.76728713, -0.07002087],
       [-0.20473975, -0.07002087],
       [ 1.06563201, -1.24637147],
       [ 0.11285319, -1.24637147],
       [ 1.28698467,  1.10632974],
       [-0.41646838,  1.10632974],
       [ 0.09360513, -1.24637147],
       [ 0.59405462, -0.07002087],
       [-2.03330517, -0.07002087],
       [ 0.32458182, -1.24637147],
       [ 0.40157405, -1.24637147],
       [-1.10939843, -0.07002087],
       [ 1.03675993, -1.24637147],
       [-0.61857297, -0.07002087],
       [ 0.44007016, -0.07002087],
       [ 1.14262424, -1.24637147],
       [-0.35872421,  1.10632974],
       [ 0.45931822,  1.10632974],
       [ 1.88367444,  1.10632974],
       [ 0.45931822, -1.24637147],
       [-0.12774752, -0.07002087],
       [ 0.04548499,  1.10632974],
       [ 0.85390339, -0.07002087],
       [ 0.15134931, -0.07002087],
       [ 0.8250313 ,  1.10632974],
       [ 0.84427936,  1.10632974],
       [-0.64744506, -1.24637147],
       [ 1.24848856, -1.24637147],
       [ 0.85390339,  1.10632974],
       [ 1.69119387,  1.10632974],
       [ 1.6334497 ,  1.10632974],
       [ 1.46021718, -1.24637147],
       [ 1.68156984, -0.07002087],
       [-0.02188321,  1.10632974],
       [ 0.87315144,  1.10632974],
       [-0.33947615, -1.24637147],
       [ 1.3639769 ,  1.10632974],
       [ 1.12337618, -1.24637147],
       [ 1.97029069, -0.07002087]])

In [9]:
#fit  a linear model using scaled values
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [10]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [11]:
reg.intercept_

np.float64(3.330238095238095)

In [12]:
#creaing a summary
summary = pd.DataFrame([["intercept"], ["SAT"], ["Rand 1 2 3"]], columns = ["Features"])
summary["weight"] = reg.intercept_, reg.coef_[0],reg.coef_[1]
summary

     Features    weight
0   intercept  3.330238
1         SAT  0.171814
2  Rand 1 2 3 -0.007030

In [13]:
#making predictions
n_data = pd.DataFrame([[1700,2], [1800,1]], columns=["SAT", "Rand 1,2,3"])
n_data

    SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [14]:
reg.predict(n_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

array([295.39979563, 312.58821497])

In [15]:
#the above output values are bigger because they are not scaled
#now lets standardize the new data using our scals
sn_data = scaler.transform(n_data)
reg.predict(sn_data)

array([3.09051403, 3.26413803])

In [32]:
snn_data = pd.DataFrame([[1700], [1800]], columns=["SAT"])
sn_data = scaler.transform(snn_data)

#Remmoving Rand 123 and compare results

In [17]:
x2 = data.drop(["Rand 1,2,3", "GPA"], axis = 1)
x2

     SAT
0   1714
1   1664
2   1760
3   1685
4   1693
..   ...
79  1936
80  1810
81  1987
82  1962
83  2050

[84 rows x 1 columns]

In [20]:
scaler.fit(x2)

StandardScaler()

In [22]:
x2_s = scaler.transform(x2)
x2_s

array([[-1.26338288],
       [-1.74458431],
       [-0.82067757],
       [-1.54247971],
       [-1.46548748],
       [-1.68684014],
       [-0.78218146],
       [-0.78218146],
       [-0.51270866],
       [ 0.04548499],
       [-1.06127829],
       [-0.67631715],
       [-1.06127829],
       [-1.28263094],
       [-0.6955652 ],
       [ 0.25721362],
       [-0.86879772],
       [-1.64834403],
       [-0.03150724],
       [-0.57045283],
       [-0.81105355],
       [-1.18639066],
       [-1.75420834],
       [-1.52323165],
       [ 1.23886453],
       [-0.18549169],
       [-0.5608288 ],
       [-0.23361183],
       [ 1.68156984],
       [-0.4934606 ],
       [-0.73406132],
       [ 0.85390339],
       [-0.67631715],
       [ 0.09360513],
       [ 0.33420585],
       [ 0.03586096],
       [-0.35872421],
       [ 1.04638396],
       [-0.65706909],
       [-0.13737155],
       [ 0.18984542],
       [ 0.04548499],
       [ 1.1618723 ],
       [-1.37887123],
       [ 1.39284898],
       [ 0.76728713],
       [-0.20473975],
       [ 1.06563201],
       [ 0.11285319],
       [ 1.28698467],
       [-0.41646838],
       [ 0.09360513],
       [ 0.59405462],
       [-2.03330517],
       [ 0.32458182],
       [ 0.40157405],
       [-1.10939843],
       [ 1.03675993],
       [-0.61857297],
       [ 0.44007016],
       [ 1.14262424],
       [-0.35872421],
       [ 0.45931822],
       [ 1.88367444],
       [ 0.45931822],
       [-0.12774752],
       [ 0.04548499],
       [ 0.85390339],
       [ 0.15134931],
       [ 0.8250313 ],
       [ 0.84427936],
       [-0.64744506],
       [ 1.24848856],
       [ 0.85390339],
       [ 1.69119387],
       [ 1.6334497 ],
       [ 1.46021718],
       [ 1.68156984],
       [-0.02188321],
       [ 0.87315144],
       [-0.33947615],
       [ 1.3639769 ],
       [ 1.12337618],
       [ 1.97029069]])

In [23]:
reg.fit(x2_s,y)

LinearRegression()

In [24]:
reg.coef_

array([0.1720369])

In [25]:
reg.intercept_

np.float64(3.330238095238095)

In [28]:
#creating a summary
summary = pd.DataFrame([["intercept_"], ["SAT"]], columns= ["Features"])
summary["weight"] = reg.intercept_, reg.coef_[0]
summary

     Features    weight
0  intercept_  3.330238
1         SAT  0.172037

In [33]:
reg.predict(sn_data)

array([3.08970998, 3.25527879])